name: parotia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.0+3
  table_calendar: ^3.2.0
  firebase_core: ^3.11.0
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  cloud_firestore: ^5.6.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/

assets:
  - assets/svgs/